#!/bin/bash

CONFIG_PATH=/etc/berry-share

openssl req -x509 -newkey rsa:4096 -keyout $CONFIG_PATH/key.pem -out $CONFIG_PATH/cert.pem -days 3650 -nodes -subj "/C=SE/L=Gothenburg/O=Example Company AB/CN=example.com"

chmod 644 $CONFIG_PATH/key.pem

